version: "3.8"
services:
  server:
    build: ./server
    container_name: server
    command: npm start
    ports:
      - "8000:8000"
    restart: always
    networks:
      - codenames
  client:
    build: ./client
    container_name: client
    command: npm start
    ports:
      - "4200:4200"
    restart: always
    networks:
      - codenames

networks:
  codenames:
    driver: bridge